import React, { useState } from 'react';
import { BookOpen, ShieldCheck, Download, CheckCircle2, X, Database, Smartphone, Laptop, FileText, Sparkles } from 'lucide-react';

interface RecoveryKitModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const RecoveryKitModal: React.FC<RecoveryKitModalProps> = ({ isOpen, onClose }) => {
  const [downloaded, setDownloaded] = useState(false);

  if (!isOpen) return null;

  const recoveryGuideMarkdown = `# QuickBill PRP
## Complete Data Safety, Backup & Disaster Recovery Guide

---

### 1. Offline-First Architecture Overview
QuickBill PRP is engineered as a local Progressive Web App (PWA) with client-side persistence powered by **IndexedDB**. 
- **Zero Cloud Latency:** All invoices, quotations, customer profiles, product masters, and MIS records remain safely on your device.
- **Works 100% Offline:** You can generate invoices, download GST PDFs, and compute MIS analytics without active internet access.

---

### 2. The 3-2-1 Business Data Backup Strategy
To ensure 100% data safety against device loss or browser resets:
1. **3 Copies of Data:** Keep the working copy on your device, plus 2 independent backup files.
2. **2 Different Media Types:** Keep one backup on your device/local drive and one on a USB flash drive or Cloud Drive (Google Drive / OneDrive).
3. **1 Off-Site Copy:** Keep a weekly backup copy emailed to your official business email or secure storage.

---

### 3. Multi-Device Workflow (Laptop ➔ Mobile ➔ Tablet)
- **Exporting from Device A:**
  1. Open QuickBill PRP > Backup & Data Safety (or Settings).
  2. Click **Export Document Data**.
  3. Select Date Range or Document Type and click **Download Export File** (\`QuickBillPRP_Export_YYYYMMDD.json\`).
- **Importing to Device B:**
  1. Open QuickBill PRP on your mobile device or secondary laptop.
  2. Click **Import Document Data**.
  3. Select the exported \`.json\` file.
  4. QuickBill PRP scans and merges all documents, new customers, and products without creating duplicate entries.

---

### 4. Emergency Disaster Recovery Protocol
If a browser is reset, computer re-formatted, or device lost:
1. Open QuickBill PRP on your new browser or device.
2. Go to **Settings > Full Backup & Restore** (or click **Import**).
3. Select your latest \`QuickBillPRP_Backup_*.json\` file.
4. Choose **Replace Data** or **Merge Data**.
5. All invoices, quotes, price histories, and settings are restored instantly.

---

*Generated by QuickBill PRP – Made by Paras R. Panchal*
`;

  const handleDownloadGuide = () => {
    const blob = new Blob([recoveryGuideMarkdown], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'QuickBill_PRP_Recovery_Guide.md';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setDownloaded(true);
    setTimeout(() => setDownloaded(false), 3000);
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-900/80 backdrop-blur-xs flex items-center justify-center p-4 animate-fadeIn">
      <div className="bg-white max-w-2xl w-full rounded-2xl shadow-2xl border border-slate-200 overflow-hidden flex flex-col max-h-[90vh]">
        {/* Header */}
        <div className="bg-gradient-to-r from-indigo-900 via-slate-900 to-slate-950 p-5 text-white flex items-center justify-between shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-indigo-600 flex items-center justify-center text-white shrink-0 shadow-xs">
              <BookOpen className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-sm font-black uppercase tracking-wider">
                QUICKBILL PRP RECOVERY KIT & DOCUMENTATION
              </h2>
              <p className="text-xs text-indigo-200">Data Safety, 3-2-1 Strategy & Multi-Device Protocol</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content Body */}
        <div className="p-6 space-y-6 overflow-y-auto flex-1 text-xs text-slate-700">
          {/* Quick Highlight Cards */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            <div className="p-3.5 rounded-xl bg-indigo-50/70 border border-indigo-100 space-y-1">
              <div className="font-extrabold text-indigo-950 text-xs flex items-center gap-1.5">
                <Database className="w-4 h-4 text-indigo-600" />
                <span>100% Offline</span>
              </div>
              <p className="text-[11px] text-slate-600">
                Data is stored in your device's private IndexedDB database with zero cloud delay.
              </p>
            </div>

            <div className="p-3.5 rounded-xl bg-amber-50/70 border border-amber-100 space-y-1">
              <div className="font-extrabold text-amber-950 text-xs flex items-center gap-1.5">
                <ShieldCheck className="w-4 h-4 text-amber-600" />
                <span>3-2-1 Strategy</span>
              </div>
              <p className="text-[11px] text-slate-600">
                Maintain working data, a USB backup, and a weekly email backup for total peace of mind.
              </p>
            </div>

            <div className="p-3.5 rounded-xl bg-emerald-50/70 border border-emerald-100 space-y-1">
              <div className="font-extrabold text-emerald-950 text-xs flex items-center gap-1.5">
                <Smartphone className="w-4 h-4 text-emerald-600" />
                <span>Multi-Device</span>
              </div>
              <p className="text-[11px] text-slate-600">
                Seamlessly export documents from Laptop and import into Mobile or Tablet.
              </p>
            </div>
          </div>

          {/* Detailed Guide Steps */}
          <div className="space-y-4 border border-slate-200 rounded-2xl p-4 bg-slate-50/50">
            <h3 className="font-black text-slate-900 text-xs uppercase tracking-wider">
              Step-by-Step Multi-Device Sync Protocol
            </h3>
            
            <div className="space-y-3 text-xs">
              <div className="flex items-start gap-2.5">
                <span className="w-5 h-5 rounded-full bg-indigo-600 text-white font-bold text-[11px] flex items-center justify-center shrink-0 mt-0.5">1</span>
                <div>
                  <strong className="text-slate-900">Create Invoices or Quotes on any device:</strong>
                  <p className="text-slate-600 text-[11px] mt-0.5">
                    Generate bills on your office PC or phone while visiting clients.
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-2.5">
                <span className="w-5 h-5 rounded-full bg-indigo-600 text-white font-bold text-[11px] flex items-center justify-center shrink-0 mt-0.5">2</span>
                <div>
                  <strong className="text-slate-900">Export Document Data:</strong>
                  <p className="text-slate-600 text-[11px] mt-0.5">
                    Go to <strong>Export Document Data</strong> and download the lightweight <code className="bg-slate-200 px-1 py-0.5 rounded-sm font-mono text-[10px]">.json</code> transfer package.
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-2.5">
                <span className="w-5 h-5 rounded-full bg-indigo-600 text-white font-bold text-[11px] flex items-center justify-center shrink-0 mt-0.5">3</span>
                <div>
                  <strong className="text-slate-900">Import on Target Device:</strong>
                  <p className="text-slate-600 text-[11px] mt-0.5">
                    Open QuickBill PRP on your other device, choose <strong>Import Document Data</strong>, and confirm. All records are merged with automatic duplicate prevention.
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Disaster Recovery Box */}
          <div className="p-4 rounded-xl bg-slate-900 text-white space-y-2">
            <div className="flex items-center justify-between">
              <span className="font-extrabold text-xs uppercase text-amber-400">Emergency Recovery</span>
              <span className="text-[10px] text-slate-400">Zero Cloud Dependency</span>
            </div>
            <p className="text-xs text-slate-300 leading-relaxed">
              If your computer is formatted or browser cache cleared, click <strong>Restore Backup</strong> in Settings, select your latest backup file, and your entire QuickBill ERP system will be restored in seconds.
            </p>
          </div>
        </div>

        {/* Footer */}
        <div className="p-4 bg-slate-50 border-t border-slate-200 flex items-center justify-between shrink-0">
          <button
            type="button"
            onClick={handleDownloadGuide}
            className="py-2.5 px-4 rounded-xl bg-white hover:bg-slate-100 border border-slate-300 text-slate-800 font-bold text-xs shadow-2xs transition flex items-center gap-2 cursor-pointer"
          >
            {downloaded ? (
              <>
                <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                <span className="text-emerald-700">Guide Downloaded (.md)</span>
              </>
            ) : (
              <>
                <Download className="w-4 h-4 text-indigo-600" />
                <span>Download Recovery Guide (.md)</span>
              </>
            )}
          </button>

          <button
            type="button"
            onClick={onClose}
            className="py-2.5 px-5 rounded-xl bg-slate-900 hover:bg-slate-800 text-white font-extrabold text-xs transition cursor-pointer"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
