import React from 'react';
import { History, User, Clock, ArrowRight } from 'lucide-react';
import { BusinessDocument } from '../../types';
import { formatDateTime, formatIndianCurrency } from '../../utils/indianNumbering';

interface DocumentHistoryModalProps {
  document: BusinessDocument | null;
  onClose: () => void;
}

export const DocumentHistoryModal: React.FC<DocumentHistoryModalProps> = ({
  document: doc,
  onClose,
}) => {
  if (!doc) return null;

  return (
    <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-sm flex items-center justify-center p-4">
      <div className="bg-white max-w-2xl w-full rounded-2xl shadow-2xl border border-slate-200 p-6 space-y-4 animate-scaleUp">
        <div className="flex items-center justify-between border-b border-slate-100 pb-3">
          <div className="flex items-center gap-2">
            <History className="w-5 h-5 text-indigo-600" />
            <div>
              <h3 className="text-base font-black text-slate-900">
                Document Audit & Change Trail
              </h3>
              <p className="text-xs text-slate-500">
                {doc.docType} No: <strong className="text-slate-800">{doc.docNumber}</strong> ({doc.customerName})
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="text-slate-400 hover:text-slate-600 font-bold p-1"
          >
            ✕
          </button>
        </div>

        {/* Creation metadata banner */}
        <div className="p-3 bg-slate-50 rounded-xl border border-slate-200 text-xs flex flex-wrap items-center justify-between gap-2">
          <div className="flex items-center gap-2">
            <User className="w-4 h-4 text-slate-500" />
            <span>
              Original Generated By: <strong>{doc.generatedByName}</strong>
            </span>
          </div>
          <div className="flex items-center gap-2 text-slate-500">
            <Clock className="w-4 h-4" />
            <span>{formatDateTime(doc.generatedAt)}</span>
          </div>
        </div>

        {/* Changes list */}
        <div className="max-h-72 overflow-y-auto space-y-3">
          {(!doc.changeHistory || doc.changeHistory.length === 0) ? (
            <div className="text-center py-8 text-xs text-slate-400">
              No modifications recorded. This document remains in its original generated state.
            </div>
          ) : (
            doc.changeHistory.map((item, idx) => (
              <div
                key={idx}
                className="p-3 rounded-xl border border-slate-200 bg-white space-y-1.5 text-xs shadow-xs"
              >
                <div className="flex items-center justify-between">
                  <div className="font-bold text-indigo-900 flex items-center gap-1.5">
                    <span className="w-2 h-2 rounded-full bg-indigo-600" />
                    <span>Edited by {item.editedByName}</span>
                  </div>
                  <span className="text-[10px] text-slate-500">{formatDateTime(item.timestamp)}</span>
                </div>

                <div className="text-slate-700 bg-indigo-50/50 p-2 rounded-lg border border-indigo-100 font-medium">
                  <strong>Reason:</strong> {item.reason}
                </div>

                {item.summary && (
                  <div className="text-[11px] text-slate-600">
                    <strong>Summary:</strong> {item.summary}
                  </div>
                )}

                {item.oldValues && item.newValues && (
                  <div className="grid grid-cols-2 gap-2 pt-1 text-[10px]">
                    <div className="p-1.5 bg-slate-50 rounded border border-slate-200 text-slate-600">
                      <div className="font-bold text-slate-500 uppercase">Prior State:</div>
                      <div>Total: ₹{Number(item.oldValues.grandTotal || 0).toLocaleString('en-IN')}</div>
                      <div>Items: {item.oldValues.itemCount}</div>
                    </div>
                    <div className="p-1.5 bg-emerald-50 rounded border border-emerald-200 text-emerald-900">
                      <div className="font-bold text-emerald-700 uppercase">New State:</div>
                      <div>Total: ₹{Number(item.newValues.grandTotal || 0).toLocaleString('en-IN')}</div>
                      <div>Items: {item.newValues.itemCount}</div>
                    </div>
                  </div>
                )}
              </div>
            ))
          )}
        </div>

        <div className="pt-2 text-right">
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-xl bg-slate-900 text-white text-xs font-bold"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
