import { Customer, Product, MISRecord, AuditLog } from '../types';
import { formatDate } from './indianNumbering';

function downloadFile(content: string, fileName: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function escapeCsvCell(val: any): string {
  if (val === null || val === undefined) return '""';
  const str = String(val);
  return `"${str.replace(/"/g, '""')}"`;
}

export function exportMISToExcel(records: MISRecord[], filenamePrefix = 'QuickBill_MIS'): void {
  const headers = [
    'Document Type',
    'Document Number',
    'Document Date',
    'Document Time',
    'Customer Name',
    'Product Details',
    'Taxable Value (₹)',
    'CGST (₹)',
    'SGST (₹)',
    'IGST (₹)',
    'Total Tax (₹)',
    'Freight (₹)',
    'Other Charges (₹)',
    'Discount (₹)',
    'Rounding Off (₹)',
    'Grand Total (₹)',
    'Status',
    'Generated By',
    'Created At',
    'Last Edited By',
    'Last Edited At',
    'Sync Status',
  ];

  const rows = records.map(r => [
    escapeCsvCell(r.documentType),
    escapeCsvCell(r.documentNumber),
    escapeCsvCell(r.documentDate),
    escapeCsvCell(r.documentTime),
    escapeCsvCell(r.customerName),
    escapeCsvCell(r.productDetailsDisplay.replace(/\n/g, ' | ')),
    escapeCsvCell(r.taxableValue.toFixed(2)),
    escapeCsvCell(r.cgst.toFixed(2)),
    escapeCsvCell(r.sgst.toFixed(2)),
    escapeCsvCell(r.igst.toFixed(2)),
    escapeCsvCell(r.totalTax.toFixed(2)),
    escapeCsvCell(r.freight.toFixed(2)),
    escapeCsvCell(r.otherCharges.toFixed(2)),
    escapeCsvCell(r.discount.toFixed(2)),
    escapeCsvCell(r.roundingOff.toFixed(2)),
    escapeCsvCell(r.grandTotal.toFixed(2)),
    escapeCsvCell(r.status),
    escapeCsvCell(r.generatedBy),
    escapeCsvCell(r.createdAt),
    escapeCsvCell(r.lastEditedBy || '-'),
    escapeCsvCell(r.lastEditedAt || '-'),
    escapeCsvCell(r.syncStatus),
  ]);

  const csvContent = [headers.join(','), ...rows.map(row => row.join(','))].join('\r\n');
  const now = new Date();
  const dateStr = now.toISOString().slice(0, 10);
  downloadFile('\uFEFF' + csvContent, `${filenamePrefix}_${dateStr}.csv`, 'text/csv;charset=utf-8;');
}

export function exportCustomersToCSV(customers: Customer[]): void {
  const headers = [
    'Customer ID',
    'Customer Name',
    'Address',
    'PIN Code',
    'GSTIN',
    'Contact Number',
    'Email',
    'State',
    'State Code',
    'Status',
    'Created Date',
  ];

  const rows = customers.map(c => [
    escapeCsvCell(c.id),
    escapeCsvCell(c.customerName),
    escapeCsvCell(c.address),
    escapeCsvCell(c.pinCode || ''),
    escapeCsvCell(c.gstin),
    escapeCsvCell(c.contactNumber),
    escapeCsvCell(c.email),
    escapeCsvCell(c.state),
    escapeCsvCell(c.stateCode),
    escapeCsvCell(c.active ? 'Active' : 'Inactive'),
    escapeCsvCell(c.createdDate),
  ]);

  const csvContent = [headers.join(','), ...rows.map(row => row.join(','))].join('\r\n');
  downloadFile('\uFEFF' + csvContent, `QuickBill_Customers_${new Date().toISOString().slice(0, 10)}.csv`, 'text/csv;charset=utf-8;');
}

export function downloadCustomerTemplateCSV(): void {
  const headers = ['Customer Name', 'Address', 'PIN Code', 'GSTIN', 'Contact Number', 'Email', 'State', 'State Code'];
  const sampleRow = [
    'Example Client Pvt Ltd',
    'Plot 101, Industrial Estate, Phase-1',
    '380001',
    '24AAAAA0000A1Z5',
    '+91 98000 00000',
    'accounts@example.com',
    'Gujarat',
    '24',
  ];

  const csvContent = [headers.join(','), sampleRow.map(escapeCsvCell).join(',')].join('\r\n');
  downloadFile('\uFEFF' + csvContent, 'Customer_Import_Template.csv', 'text/csv;charset=utf-8;');
}

export function exportProductsToCSV(products: Product[]): void {
  const headers = [
    'Product ID',
    'Product Name',
    'Product Description',
    'HSN/SAC',
    'Default GST Rate (%)',
    'Default Base Price (₹)',
    'Status',
    'Created Date',
  ];

  const rows = products.map(p => [
    escapeCsvCell(p.id),
    escapeCsvCell(p.productName),
    escapeCsvCell(p.productDescription),
    escapeCsvCell(p.hsnSac),
    escapeCsvCell(p.defaultGstRate),
    escapeCsvCell(p.defaultBasePrice.toFixed(2)),
    escapeCsvCell(p.active ? 'Active' : 'Inactive'),
    escapeCsvCell(p.createdDate),
  ]);

  const csvContent = [headers.join(','), ...rows.map(row => row.join(','))].join('\r\n');
  downloadFile('\uFEFF' + csvContent, `QuickBill_Products_${new Date().toISOString().slice(0, 10)}.csv`, 'text/csv;charset=utf-8;');
}

export function downloadProductTemplateCSV(): void {
  const headers = ['Product Name', 'Product Description', 'HSN/SAC', 'Default GST Rate', 'Default Base Price'];
  const sampleRow = [
    'Sample Item Specification',
    'Standard Commercial Goods Description',
    '84818030',
    '18',
    '1000.00',
  ];

  const csvContent = [headers.join(','), sampleRow.map(escapeCsvCell).join(',')].join('\r\n');
  downloadFile('\uFEFF' + csvContent, 'Product_Import_Template.csv', 'text/csv;charset=utf-8;');
}
